version: 9.9.9.{build}
skip_non_tags: true
build: off
test: off
artifacts:
- path: dist\windows\QMK_Firmware_Flasher_setup.exe
  name: setup
install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - cmd: dist-win32.bat
deploy:
- provider: GitHub
  auth_token:
    secure: MBivjW4RpFI0TRdHQb+PchNY5yQte+IOqerViefhEo6XqTgH8nAIvC9ibShVik8s
  artifact: setup
  draft: true
  prerelease: true
  force_update: true